Expose :c:func:`PyErr_ChainExceptions` in the stable API. Patch by Pablo
Galindo.
